# Pandas & NumPy

## Installing numpy and pandas

In [2]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 14.4 MB/s eta 0:00:00m eta 0:00:010:00:01
Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 12.6 MB/s eta 0:00:00m eta 0:00:010:0101
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Note: you may need to restart the kernel to use updated packages.


In [26]:
import numpy as np

In [8]:
list1 = [20, 30, 40]
list1

[20, 30, 40]

In [9]:
arr1 = np.array(list1)
arr1

array([20, 30, 40])

list object multiplied by integer will print the list by that multiple, unlike arrays

In [15]:
list1 * 3

[20, 30, 40, 20, 30, 40, 20, 30, 40]

In [14]:
arr1 * 3

array([ 60,  90, 120])

In [17]:
list2 = [list1, list1]
list2

[[20, 30, 40], [20, 30, 40]]

arr2 is a matrix

In [19]:
arr2 = np.array(list2)
arr2

array([[20, 30, 40],
       [20, 30, 40]])

indexing:

In [22]:
arr2[1][2]

40

In [23]:
list2[0][2]

40

----

In [27]:
import pandas as pd

we are creating instances of the classes (capitalised)

In [31]:
x = pd.Series([10, 20, 30, 40])
x

0    10
1    20
2    30
3    40
dtype: int64

In [33]:
data = [['Adrian', 20], ['Bethany', 23], ['Chloe', 41]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0   Adrian   20
1  Bethany   23
2    Chloe   41

fillna is a method from the Series class

In [35]:
df.fillna(0)

Name  Age
0   Adrian   20
1  Bethany   23
2    Chloe   41